from enum import Enum
from typing import Dict, Tuple
from BaseClasses import Item, ItemClassification

class SignalisItem(Item):
    game: str = "Signalis"

class SignalisItemClassification(Enum):
    key = 1 # Key item
    ammo = 2 # Includes disposable stun rods and thermite flares
    health = 3 
    weapon = 4 # Includes items required to get weapons (Hunter's Key, Weapon Case, Small Bottle)
    lore = 5 # Items that can be picked up/stored but serve no function other than flavor (The King in Yellow, Photo of Alina)

item_dict: Dict[str, Tuple[ItemClassification, SignalisItemClassification, int]] = {
    "Photograph (Ariane)": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Airlock Key (Broken)": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Adhesive Tape": (ItemClassification.progression, SignalisItemClassification.key, 2),
    "The King in Yellow": (ItemClassification.filler, SignalisItemClassification.lore, 1),
    "Photograph (Alina)": (ItemClassification.filler, SignalisItemClassification.lore, 1),
    "Classroom Key": (ItemClassification.progression, SignalisItemClassification.key, 2),
    "Aperture Card": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Protektor Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Receptionist Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Broken Key, Top Half": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Broken Key, Bottom Half": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "East Wing Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Identification Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Mensa Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Service Hatch Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "West Wing Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Examination Room Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Incinerator Room Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Air Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Blank Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Fire Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Gold Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Water Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Pump Room Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "10mm Socket": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Socket Wrench Handle": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Video Cassette": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Eagle Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Fuse": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Maintenance Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Hummingbird Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Library Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Administrator's Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Broken Music Cassette": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Owl Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Island Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Postbox Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Weapon Case": (ItemClassification.useful, SignalisItemClassification.weapon, 1),
    "Hunters Key": (ItemClassification.useful, SignalisItemClassification.weapon, 1),
    "Astrolabe": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Shutter Gate Handle": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Workshop Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Large Wooden Doll": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Wooden Doll": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Small Wooden Doll": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Incense": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Plate of Balance": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Plate of Eternity": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Plate of Flesh": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Plate of Knowledge": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Plate of Love": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Plate of Sacrifice": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Wedding Ring": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Regent's Ring": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Serpent Ring": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Small Bottle": (ItemClassification.useful, SignalisItemClassification.weapon, 1),
    "Developing Tank": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Developer Fluid": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Blue Diskette": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Red Diskette": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Patient Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Dial Ring": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Store Key": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Death": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Lovers": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Moon": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Star": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Sun": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Tower": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Acetone": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Handwheel": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Flare Gun": (ItemClassification.useful, SignalisItemClassification.weapon, 1),
    "Flashlight Module": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Key of Eternity": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Key of Sacrifice": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Key of Love": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Eidetic Module": (ItemClassification.useful, SignalisItemClassification.key, 1),
    "Radio Module": (ItemClassification.progression, SignalisItemClassification.key, 1),
    "Pistol": (ItemClassification.progression, SignalisItemClassification.weapon, 1),
    "Shotgun": (ItemClassification.useful, SignalisItemClassification.weapon, 1),
    "Submachine Gun": (ItemClassification.useful, SignalisItemClassification.weapon, 1),
    "Repair Patch": (ItemClassification.filler, SignalisItemClassification.health, 17),
    "10mm Ammo": (ItemClassification.filler, SignalisItemClassification.ammo, 23),
    "Disposable Stun Prod": (ItemClassification.filler, SignalisItemClassification.ammo, 13),
    "Repair Spray+": (ItemClassification.filler, SignalisItemClassification.health, 5),
    "Shotgun Rounds": (ItemClassification.filler, SignalisItemClassification.ammo, 15),
    "Autoinjector": (ItemClassification.filler, SignalisItemClassification.health, 8),
    "Thermite Flare": (ItemClassification.filler, SignalisItemClassification.ammo, 5),
    "Repair Spray": (ItemClassification.filler, SignalisItemClassification.health, 20),
    "12mm Ammo": (ItemClassification.filler, SignalisItemClassification.ammo, 11),
    "Nitro Express Ammo": (ItemClassification.filler, SignalisItemClassification.ammo, 5),
    "8mm Ammo": (ItemClassification.filler, SignalisItemClassification.ammo, 4),
    "Signal Flare Shells": (ItemClassification.filler, SignalisItemClassification.ammo, 4),
    "Grenade Shells": (ItemClassification.filler, SignalisItemClassification.ammo, 4),
    "Rusted Key": (ItemClassification.progression, SignalisItemClassification.key, 1)
}