from enum import Enum
from typing import Dict, Tuple
from BaseClasses import Location

class SignalisLocation(Location):
    game: str = "Signalis"

class SignalisLocationClassification(Enum):
    key = 1 # Key item
    ammo = 2 # Includes disposable stun rods and thermite flares
    health = 3 
    weapon = 4 # Includes items required to get weapons (Hunter's Key, Weapon Case, Small Bottle)
    lore = 5 # Items that can be picked up/stored but serve no function other than flavor (The King in Yellow, Photo of Alina)

location_dict: Dict[str, Tuple[SignalisLocationClassification, str]] = {
    # Penrose Wreck Locations
    "Photo of Ariane": (SignalisLocationClassification.key, "Penrose Wreck"),
    "Adhesive Tape (Penrose)": (SignalisLocationClassification.key, "Penrose Wreck"),
    "Broken Airlock Key": (SignalisLocationClassification.key, "Penrose Wreck"),
    "The King in Yellow": (SignalisLocationClassification.lore, "Penrose Wreck"),

    # Installation AEON Locations
    "Receiptionist Key": (SignalisLocationClassification.key, "Installation AEON"),
    "Protektor Key": (SignalisLocationClassification.key, "Installation AEON"),
    "Pistol": (SignalisLocationClassification.weapon, "Installation AEON"),
    "Aperture Card": (SignalisLocationClassification.key, "Installation AEON"),
    "Classroom Key (Installation AEON)": (SignalisLocationClassification.key, "Installation AEON"),
    "Repair Patch (Installation AEON - Aula)": (SignalisLocationClassification.health, "Installation AEON"),
    "10mm Ammo (Installation AEON - Aula)": (SignalisLocationClassification.ammo, "Installation AEON"),

    # Worker Barracks Locations
    "Receive Photo of Alina": (SignalisLocationClassification.lore, "Worker Barracks"),
    "Service Hatch Key": (SignalisLocationClassification.key, "Worker Barracks"),
    "East Wing Key": (SignalisLocationClassification.key, "Worker Barracks"),
    "10mm Ammo (Worker Barracks - Office)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "Disposable Stun Prod (Worker Barracks - Office)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "Repair Patch (Worker Barracks - First Aid)": (SignalisLocationClassification.health, "Worker Barracks"),
    "Plate of Eternity": (SignalisLocationClassification.key, "Worker Barracks"),
    "Radio Module": (SignalisLocationClassification.key, "Worker Barracks"),
    "Identification Key": (SignalisLocationClassification.key, "Worker Barracks"),
    "Repair Patch (Worker Barracks - Protektor Bathroom)": (SignalisLocationClassification.health, "Worker Barracks"),
    "10mm Ammo (Worker Barracks - Store Room)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "Mensa Key": (SignalisLocationClassification.key, "Worker Barracks"),
    "10mm Ammo (Worker Barracks - Mensa, Top of Room)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "10mm Ammo (Worker Barracks - Mensa, Bottom of Room)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "Repair Patch (Worker Barracks - Mensa)": (SignalisLocationClassification.health, "Worker Barracks"),
    "West Wing Key": (SignalisLocationClassification.key, "Worker Barracks"),
    "Disposable Stun Prod (Worker Barracks - Rationing Office)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "Broken Key, Top Half": (SignalisLocationClassification.key, "Worker Barracks"),
    "10mm Ammo (Worker Barracks - Lockers)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "Broken Key, Bottom Half": (SignalisLocationClassification.key, "Worker Barracks"),
    "Disposable Stun Prod (Worker Barracks - Registry)": (SignalisLocationClassification.ammo, "Worker Barracks"),
    "Repair Spray+ (Worker Barracks - Isolation)": (SignalisLocationClassification.health, "Worker Barracks"),
    "Key of Love": (SignalisLocationClassification.key, "Worker Barracks"),
    
    # Hospital Wing Locations
    "Shotgun": (SignalisLocationClassification.weapon, "Hospital Wing"),
    "Shotgun Rounds (Hospital Wing - HDU 02, Northwest)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Shotgun Rounds (Hospital Wing - HDU 02, Southwest)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Shotgun Rounds (Hospital Wing - Morgue)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Pump Room Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "Repair Spray (Hospital Wing - Store Room)": (SignalisLocationClassification.health, "Hospital Wing"),
    "Repair Spray (Hospital Wing - HDU 02)": (SignalisLocationClassification.health, "Hospital Wing"),
    "Socket Wrench Handle": (SignalisLocationClassification.key, "Hospital Wing"),
    "Autoinjector (Hospital Wing - ICU 01)": (SignalisLocationClassification.health, "Hospital Wing"),
    "10mm Ammo (Hospital Wing - HDU 02)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Repair Patch (Hospital Wing - HDU 02)": (SignalisLocationClassification.health, "Hospital Wing"),
    "Disposable Stun Prod (Hospital Wing - Nurse Station)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Eidetic Module": (SignalisLocationClassification.key, "Hospital Wing"),
    "Incinerator Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "Gold Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "Disposable Stun Prod (Hospital Wing - Pump Room)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Disposable Stun Prod (Hospital Wing - Flooded Office)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Water Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "Repair Patch (Hospital Wing - Flooded Bathroom)": (SignalisLocationClassification.health, "Hospital Wing"),
    "10mm Ammo (Hospital Wing - Flooded Store Room)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "10mm Ammo (Hospital Wing - Sleeping Ward)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Blank Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "Examination Room Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "Video Cassette": (SignalisLocationClassification.key, "Hospital Wing"),
    "12mm Ammo (Hospital Wing - Sleeping Ward)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Air Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "Autoinjector (Hospital Wing - Exam Room)": (SignalisLocationClassification.health, "Hospital Wing"),
    "10mm Socket": (SignalisLocationClassification.key, "Hospital Wing"),
    "Thermite Flare (Hospital Wing - Incinerator Room)": (SignalisLocationClassification.ammo, "Hospital Wing"),
    "Fire Key": (SignalisLocationClassification.key, "Hospital Wing"),
    "10mm Ammo (Hospital Wing - Surgery)": (SignalisLocationClassification.ammo, "Hospital Wing"),

    # Proktektor Levels Locations
    "Maintenance Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "Thermite Flare (Protektor Levels - Maintenance Office)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - Cleaning Room Hallway)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "12mm Ammo (Protektor Levels - STCR Dorm, 6th Floor)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Repair Patch (Protektor Levels - Cleaning Room)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Autoinjector (Protektor Levels - Cleaning Room)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Repair Patch (Protektor Levels - Cleaning Room Hallway)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Repair Patch (Protektor Levels - Workshop Hallway)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Disposable Stun Prod (Protektor Levels - ARAR Dorm)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - ARAR Dorm)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Shotgun Rounds (Protektor Levels - ARAR Dorm)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Repair Spray (Protektor Levels - South STAR Dorm)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Autoinjector (Protektor Levels - South STAR Dorm)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Shotgun Rounds (Protektor Levels - Dining Room Hallway)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - Dining Room Hallway)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - Dining Room)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Fuse": (SignalisLocationClassification.key, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - East STAR Dorm)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Shutter Gate Handle": (SignalisLocationClassification.key, "Protektor Levels"),
    "Repair Spray+ (Protektor Levels - FKLR Bedroom)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Disposable Stun Prod (Protektor Levels - FKLR Bedroom)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - FKLR Bedroom)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Flashlight Module": (SignalisLocationClassification.key, "Protektor Levels"),
    "Astrolabe": (SignalisLocationClassification.key, "Protektor Levels"),
    "Repair Spray (Protektor Levels - Library)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Hummingbird Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "Disposable Stun Prod (Protektor Levels - KLBR Study)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Eagle Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "Autoinjector (Protektor Levels - Repair Bay)": (SignalisLocationClassification.health, "Protektor Levels"),
    "Shotgun Rounds (Protektor Levels - Shooting Range)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "12mm Ammo (Protektor Levels - Shooting Range)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Weapon Case": (SignalisLocationClassification.weapon, "Protektor Levels"),
    "Island Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - Protektor Archive)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Hunter's Key": (SignalisLocationClassification.weapon, "Protektor Levels"),
    "Adhesive Tape (Protektor Levels)": (SignalisLocationClassification.key, "Protektor Levels"),
    "Shotgun Rounds (Protektor Levels - ADLR Bedroom)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Shotgun Rounds (Protektor Levels - STCR Dorm, 8th Floor)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Repair Spray+ (Protektor Levels - STCR Dorm, 8th Floor)": (SignalisLocationClassification.health, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - STCR Dorm, 8th Floor)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Repair Spray (Protektor Levels - STCR Dorm, 8th Floor)": (SignalisLocationClassification.health, "Protektor Levels"),
    "12mm Ammo (Protektor Levels - STCR Dorm, 8th Floor)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Key of Eternity": (SignalisLocationClassification.key, "Protektor Levels"),
    "Shotgun Rounds (Protektor Levels - KLBR Bedroom)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Postbox Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "Administrator's Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "Owl Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "Disposable Stun Prod (Protektor Levels - EULR Dorm)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Broken Music Cassette": (SignalisLocationClassification.key, "Protektor Levels"),
    "Workshop Key": (SignalisLocationClassification.key, "Protektor Levels"),
    "12mm Ammo (Protektor Levels - Workshop)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "10mm Ammo (Protektor Levels - Workshop)": (SignalisLocationClassification.ammo, "Protektor Levels"),
    "Library Key": (SignalisLocationClassification.key, "Protektor Levels"),

    # Mines Locations
    "Nitro Express Ammo (Mineshaft - Wire Room)": (SignalisLocationClassification.ammo, "Mines"),
    "Repair Spray (Mineshaft - Save Room)": (SignalisLocationClassification.health, "Mines"),
    "Flare Gun": (SignalisLocationClassification.weapon, "Mines"),
    "Signal Flare Shells (Mineshaft - Save Room)": (SignalisLocationClassification.ammo, "Mines"),
    "Repair Spray (Mineshaft - STAR/EULR Room)": (SignalisLocationClassification.health, "Mines"),
    "12mm Ammo (Mineshaft - STAR/EULR Room)": (SignalisLocationClassification.ammo, "Mines"),
    "10mm Ammo (Mineshaft - STAR/EULR Room)": (SignalisLocationClassification.ammo, "Mines"),
    "Repair Spray (Mineshaft - Hatch Room)": (SignalisLocationClassification.health, "Mines"),
    "10mm Ammo (Mineshaft - Hole Room)": (SignalisLocationClassification.ammo, "Mines"),
    "Repair Spray (Mineshaft - Hole Room)": (SignalisLocationClassification.health, "Mines"),

    # Nowhere Locations
    "Repair Spray (Nowhere - Morgue)": (SignalisLocationClassification.health, "Nowhere"),
    "Autoinjector (Nowhere - Altar)": (SignalisLocationClassification.health, "Nowhere"),
    "10mm Ammo (Nowhere - Operating Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "12mm Ammo (Nowhere - Operating Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Disposable Stun Prod (Nowhere - Blood Tub Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Large Wooden Doll": (SignalisLocationClassification.key, "Nowhere"),
    "Repair Patch (Nowhere - Flesh Hole)": (SignalisLocationClassification.health, "Nowhere"),
    "Nitro Express Ammo (Nowhere - Microphone Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Wedding Ring": (SignalisLocationClassification.key, "Nowhere"),
    "Thermite Flare (Nowhere - Save Room After Chimera Boss)": (SignalisLocationClassification.ammo, "Nowhere"),
    "10mm Ammo (Nowhere - Save Room After Chimera Boss)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Repair Patch (Nowhere - Cage Piles #1)": (SignalisLocationClassification.health, "Nowhere"),
    "Disposable Stun Rod (Nowhere - Cage Piles #1)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Signal Flare Shells (Nowhere - Red Ladder Up)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Repair Spray+ (Nowhere - Tentacle Room)": (SignalisLocationClassification.health, "Nowhere"),
    "Regent's Ring": (SignalisLocationClassification.key, "Nowhere"),
    "Small Bottle": (SignalisLocationClassification.weapon, "Nowhere"),
    "Repair Spray (Nowhere - Barbwire Room #1)": (SignalisLocationClassification.health, "Nowhere"),
    "Plate of Flesh": (SignalisLocationClassification.key, "Nowhere"),
    "Rusted Key": (SignalisLocationClassification.key, "Nowhere"),
    "Serpent Ring": (SignalisLocationClassification.key, "Nowhere"),
    "Shotgun Rounds (Nowhere - Dark Hall)": (SignalisLocationClassification.ammo, "Nowhere"),
    "10mm Ammo (Nowhere - Cage Piles #2)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Nitro Express Ammo (Nowhere - Cage Piles #2)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Signal Flare Shells (Nowhere - Crowded Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Small Wooden Doll": (SignalisLocationClassification.key, "Nowhere"),
    "Shotgun Rounds (Nowhere - Crowded Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Repair Spray+ (Nowhere - Hummingbird Corridor)": (SignalisLocationClassification.health, "Nowhere"),
    "Shotgun Rounds (Nowhere - Hummingbird Corridor)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Grenade Shells (Nowhere - Lamp Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Incense": (SignalisLocationClassification.key, "Nowhere"),
    "10mm Ammo (Nowhere - Empress Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Plate of Balance": (SignalisLocationClassification.key, "Nowhere"),
    "Plate of Knowledge": (SignalisLocationClassification.key, "Nowhere"),
    "12mm Ammo (Nowhere - Interrogation Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Wooden Doll": (SignalisLocationClassification.key, "Nowhere"),
    "Grenade Shells (Nowhere - Interrogation Room)": (SignalisLocationClassification.ammo, "Nowhere"),
    "Repair Spray (Nowhere - Barbwire Room #2)": (SignalisLocationClassification.health, "Nowhere"),
    "Plate of Sacrifice": (SignalisLocationClassification.key, "Nowhere"),
    "Plate of Love": (SignalisLocationClassification.key, "Nowhere"),

    # Corrupted Installation AEON Locations
    "Grenade Shells (Corrupted Installation Aeon - Classroom 4B)": (SignalisLocationClassification.ammo, "Corrupted Installation AEON"),
    "Classroom Key (Corrupted Installation Aeon)": (SignalisLocationClassification.key, "Corrupted Installation AEON"),

    # Rotfront Locations
    "Thermite Flare (Rotfront - Blockwart Bedroom)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Repair Patch (Rotfront - Blockwart Bedroom)": (SignalisLocationClassification.health, "Rotfront"),
    "Submachine Gun": (SignalisLocationClassification.weapon, "Rotfront"),
    "8mm Ammo (Rotfront - Blockwart Office)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Grenade Shells (Rotfront - Ruined Apartment)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Shotgun Rounds (Rotfront - Ruined Apartment)": (SignalisLocationClassification.ammo, "Rotfront"),
    "10mm Ammo (Rotfront - Dormitory)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Repair Spray (Rotfront - Dormitory)": (SignalisLocationClassification.health, "Rotfront"),
    "Repair Spray (Rotfront - Apartment North of Blue Hallway)": (SignalisLocationClassification.health, "Rotfront"),
    "12mm Ammo (Rotfront - Apartment North of Blue Hallway)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Handwheel": (SignalisLocationClassification.key, "Rotfront"),
    "Nitro Express Ammo (Rotfront - Apartment North of Blue Hallway)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Developing Tank": (SignalisLocationClassification.key, "Rotfront"),
    "Repair Spray+ (Rotfront - Atrium)": (SignalisLocationClassification.health, "Rotfront"),
    "Signal Flare Shells (Rotfront - Hospital Hallway)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Autoinjector (Rotfront - Hospital Room)": (SignalisLocationClassification.health, "Rotfront"),
    "Store Key": (SignalisLocationClassification.key, "Rotfront"),
    "Star": (SignalisLocationClassification.key, "Rotfront"),
    "12mm Ammo (Rotfront - Garbage Chute)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Blue Diskette": (SignalisLocationClassification.key, "Rotfront"),
    "Acetone": (SignalisLocationClassification.key, "Rotfront"),
    "Disposable Stun Prod (Rotfront - Meat Grinder)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Repair Spray (Rotfront - Public House)": (SignalisLocationClassification.health, "Rotfront"),
    "8mm Ammo (Rotfront - Public House)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Shotgun Rounds (Rotfront - Public House)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Tower": (SignalisLocationClassification.key, "Rotfront"),
    "10mm Ammo (Rotfront - Metro Platform)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Disposable Stun Prod (Rotfront - Metro Platform)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Repair Spray (Rotfront - Computer Store)": (SignalisLocationClassification.health, "Rotfront"),
    "Patient Key": (SignalisLocationClassification.key, "Rotfront"),
    "12mm Ammo (Rotfront - Fire Escape)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Disposable Stun Prod (Rotfront - Apartment North of Alley)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Repair Spray (Rotfront - Apartment North of Alley)": (SignalisLocationClassification.health, "Rotfront"),
    "Thermite Flare (Rotfront - Butterfly Room)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Nitro Express Ammo (Rotfront - Butterfly Room)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Shotgun Rounds (Rotfront - Dentist Room)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Repair Patch (Rotfront - Dentist Room)": (SignalisLocationClassification.health, "Rotfront"),
    "Red Diskette": (SignalisLocationClassification.key, "Rotfront"),
    "8mm Ammo (Rotfront - Dentist Room)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Moon": (SignalisLocationClassification.key, "Rotfront"),
    "8mm Ammo (Rotfront - Photo Store)": (SignalisLocationClassification.ammo, "Rotfront"),
    "Developer Fluid": (SignalisLocationClassification.key, "Rotfront"),
    "Sun": (SignalisLocationClassification.key, "Rotfront"),
    "Death": (SignalisLocationClassification.key, "Rotfront"),
    "Autoinjector (Rotfront - Book Store)": (SignalisLocationClassification.health, "Rotfront"),
    "Key of Sacrifice": (SignalisLocationClassification.key, "Rotfront"),
    "Lovers": (SignalisLocationClassification.key, "Rotfront"),
    "Dial": (SignalisLocationClassification.key, "Rotfront"),
}