from enum import Enum
from typing import Dict, List, Tuple
from BaseClasses import Location

class SignalisLocation(Location):
    game: str = "Signalis"

class SignalisLocationClassification(Enum):
    key = 1 # Key item
    ammo = 2 # Includes disposable stun rods and thermite flares
    health = 3 
    weapon = 4 # Includes items required to get weapons (Hunter's Key, Weapon Case, Small Bottle)
    lore = 5 # Items that can be picked up/stored but serve no function other than flavor (The King in Yellow, Photo of Alina)

location_dict: Dict[str, SignalisLocationClassification] = {
    # Penrose Wreck Locations
    "Photo of Ariane": SignalisLocationClassification.key,
    "Adhesive Tape (Penrose)": SignalisLocationClassification.key,
    "Broken Airlock Key": SignalisLocationClassification.key,
    "The King in Yellow": SignalisLocationClassification.lore,

    # Installation AEON Locations
    "Receiptionist Key": SignalisLocationClassification.key,
    "Protektor Key": SignalisLocationClassification.key,
    "Pistol": SignalisLocationClassification.weapon,
    "Aperture Card": SignalisLocationClassification.key,
    "Classroom Key (Installation AEON)": SignalisLocationClassification.key,
    "Repair Patch (Installation AEON - Aula)": SignalisLocationClassification.health,
    "10mm Ammo (Installation AEON - Aula)": SignalisLocationClassification.ammo,

    # Worker Barracks Locations
    "Receive Photo of Alina": SignalisLocationClassification.lore,
    "Service Hatch Key": SignalisLocationClassification.key,
    "East Wing Key": SignalisLocationClassification.key,
    "10mm Ammo (Worker Barracks - Office)": SignalisLocationClassification.ammo,
    "Disposable Stun Prod (Worker Barracks - Office)": SignalisLocationClassification.ammo,
    "Repair Patch (Worker Barracks - First Aid)": SignalisLocationClassification.health,
    "Plate of Eternity": SignalisLocationClassification.key,
    "Radio Module": SignalisLocationClassification.key,
    "Identification Key": SignalisLocationClassification.key,
    "Repair Patch (Worker Barracks - Protektor Bathroom)": SignalisLocationClassification.health,
    "10mm Ammo (Worker Barracks - Store Room)": SignalisLocationClassification.ammo,
    "Mensa Key": SignalisLocationClassification.key,
    "10mm Ammo (Worker Barracks - Mensa, Top of Room)": SignalisLocationClassification.ammo,
    "10mm Ammo (Worker Barracks - Mensa, Bottom of Room)": SignalisLocationClassification.ammo,
    "Repair Patch (Worker Barracks - Mensa)": SignalisLocationClassification.health,
    "West Wing Key": SignalisLocationClassification.key,
    "Disposable Stun Prod (Worker Barracks - Rationing Office)": SignalisLocationClassification.ammo,
    "Broken Key, Top Half": SignalisLocationClassification.key,
    "10mm Ammo (Worker Barracks - Lockers)": SignalisLocationClassification.ammo,
    "Broken Key, Bottom Half": SignalisLocationClassification.key,
    "Disposable Stun Prod (Worker Barracks - Registry)": SignalisLocationClassification.ammo,
    "Repair Spray+ (Worker Barracks - Isolation)": SignalisLocationClassification.health,
    "Key of Love": SignalisLocationClassification.key,
    
    # Hospital Wing Locations
    "Shotgun": SignalisLocationClassification.weapon,
    "Shotgun Rounds (Hospital Wing - HDU 02, Northwest)": SignalisLocationClassification.ammo,
    "Shotgun Rounds (Hospital Wing - HDU 02, Southwest)": SignalisLocationClassification.ammo,
    "Shotgun Rounds (Hospital Wing - Morgue)": SignalisLocationClassification.ammo,
    "Pump Room Key": SignalisLocationClassification.key,
    "Repair Spray (Hospital Wing - Store Room)": SignalisLocationClassification.health,
    "Repair Spray (Hospital Wing - HDU 02)": SignalisLocationClassification.health,
    "Socket Wrench Handle": SignalisLocationClassification.key,
    "Autoinjector (Hospital Wing - ICU 01)": SignalisLocationClassification.health,
    "10mm Ammo (Hospital Wing - HDU 02)": SignalisLocationClassification.ammo,
    "Repair Patch (Hospital Wing - HDU 02)": SignalisLocationClassification.health,
    "Disposable Stun Prod (Hospital Wing - Nurse Station)": SignalisLocationClassification.ammo,
    "Eidetic Module": SignalisLocationClassification.key,
    "Incinerator Key": SignalisLocationClassification.key,
    "Gold Key": SignalisLocationClassification.key,
    "Disposable Stun Prod (Hospital Wing - Pump Room)": SignalisLocationClassification.ammo,
    "Disposable Stun Prod (Hospital Wing - Flooded Office)": SignalisLocationClassification.ammo,
    "Water Key": SignalisLocationClassification.key,
    "Repair Patch (Hospital Wing - Flooded Bathroom)": SignalisLocationClassification.health,
    "10mm Ammo (Hospital Wing - Flooded Store Room)": SignalisLocationClassification.ammo,
    "10mm Ammo (Hospital Wing - Sleeping Ward)": SignalisLocationClassification.ammo,
    "Blank Key": SignalisLocationClassification.key,
    "Examination Room Key": SignalisLocationClassification.key,
    "Video Cassette": SignalisLocationClassification.key,
    "12mm Ammo (Hospital Wing - Sleeping Ward)": SignalisLocationClassification.ammo,
    "Air Key": SignalisLocationClassification.key,
    "Autoinjector (Hospital Wing - Exam Room)": SignalisLocationClassification.health,
    "10mm Socket": SignalisLocationClassification.key,
    "Thermite Flare (Hospital Wing - Incinerator Room)": SignalisLocationClassification.ammo,
    "Fire Key": SignalisLocationClassification.key,
    "10mm Ammo (Hospital Wing - Surgery)": SignalisLocationClassification.ammo,

    # Proktektor Levels Locations
    "Maintenance Key": SignalisLocationClassification.key,
    "Thermite Flare (Protektor Levels - Maintenance Office)": SignalisLocationClassification.ammo,
    "10mm Ammo (Protektor Levels - Cleaning Room Hallway)": SignalisLocationClassification.ammo,
    "12mm Ammo (Protektor Levels - STCR Dorm, 6th Floor)": SignalisLocationClassification.ammo,
    "Repair Patch (Protektor Levels - Cleaning Room)": SignalisLocationClassification.health,
    "Autoinjector (Protektor Levels - Cleaning Room)": SignalisLocationClassification.health,
    "Repair Patch (Protektor Levels - Cleaning Room Hallway)": SignalisLocationClassification.health,
    "Repair Patch (Protektor Levels - Workshop Hallway)": SignalisLocationClassification.health,
    "Disposable Stun Prod (Protektor Levels - ARAR Dorm)": SignalisLocationClassification.ammo,
    "10mm Ammo (Protektor Levels - ARAR Dorm)": SignalisLocationClassification.ammo,
    "Shotgun Rounds (Protektor Levels - ARAR Dorm)": SignalisLocationClassification.ammo,
    "Repair Spray (Protektor Levels - South STAR Dorm)": SignalisLocationClassification.health,
    "Autoinjector (Protektor Levels - South STAR Dorm)": SignalisLocationClassification.health,
    "Shotgun Rounds (Protektor Levels - Dining Room Hallway)": SignalisLocationClassification.ammo,
    "10mm Ammo (Protektor Levels - Dining Room Hallway)": SignalisLocationClassification.ammo,
    "10mm Ammo (Protektor Levels - Dining Room)": SignalisLocationClassification.ammo,
    "Fuse": SignalisLocationClassification.key,
    "10mm Ammo (Protektor Levels - East STAR Dorm)": SignalisLocationClassification.ammo,
    "Shutter Gate Handle": SignalisLocationClassification.key,
    "Repair Spray+ (Protektor Levels - FKLR Bedroom)": SignalisLocationClassification.health,
    "Disposable Stun Prod (Protektor Levels - FKLR Bedroom)": SignalisLocationClassification.ammo,
    "10mm Ammo (Protektor Levels - FKLR Bedroom)": SignalisLocationClassification.ammo,
    "Flashlight Module": SignalisLocationClassification.key,
    "Astrolabe": SignalisLocationClassification.key,
    "Repair Spray (Protektor Levels - Library)": SignalisLocationClassification.health,
    "Hummingbird Key": SignalisLocationClassification.key,
    "Disposable Stun Prod (Protektor Levels - KLBR Study)": SignalisLocationClassification.ammo,
    "Eagle Key": SignalisLocationClassification.key,
    "Autoinjector (Protektor Levels - Repair Bay)": SignalisLocationClassification.health,
    "Shotgun Rounds (Protektor Levels - Shooting Range)": SignalisLocationClassification.ammo,
    "12mm Ammo (Protektor Levels - Shooting Range)": SignalisLocationClassification.ammo,
    "Weapon Case": SignalisLocationClassification.weapon,
    "Island Key": SignalisLocationClassification.key,
    "10mm Ammo (Protektor Levels - Protektor Archive)": SignalisLocationClassification.ammo,
    "Hunter's Key": SignalisLocationClassification.weapon,
    "Adhesive Tape (Protektor Levels)": SignalisLocationClassification.key,
    "Shotgun Rounds (Protektor Levels - ADLR Bedroom)": SignalisLocationClassification.ammo,
    "Shotgun Rounds (Protektor Levels - STCR Dorm, 8th Floor)": SignalisLocationClassification.ammo,
    "Repair Spray+ (Protektor Levels - STCR Dorm, 8th Floor)": SignalisLocationClassification.health,
    "10mm Ammo (Protektor Levels - STCR Dorm, 8th Floor)": SignalisLocationClassification.ammo,
    "Repair Spray (Protektor Levels - STCR Dorm, 8th Floor)": SignalisLocationClassification.health,
    "12mm Ammo (Protektor Levels - STCR Dorm, 8th Floor)": SignalisLocationClassification.ammo,
    "Key of Eternity": SignalisLocationClassification.key,
    "Shotgun Rounds (Protektor Levels - KLBR Bedroom)": SignalisLocationClassification.ammo,
    "Postbox Key": SignalisLocationClassification.key,
    "Administrator's Key": SignalisLocationClassification.key,
    "Owl Key": SignalisLocationClassification.key,
    "Disposable Stun Prod (Protektor Levels - EULR Dorm)": SignalisLocationClassification.ammo,
    "Broken Music Cassette": SignalisLocationClassification.key,
    "Workshop Key": SignalisLocationClassification.key,
    "12mm Ammo (Protektor Levels - Workshop)": SignalisLocationClassification.ammo,
    "10mm Ammo (Protektor Levels - Workshop)": SignalisLocationClassification.ammo,
    "Library Key": SignalisLocationClassification.key,

    # Mines Locations
    "Nitro Express Ammo (Mineshaft - Wire Room)": SignalisLocationClassification.ammo,
    "Repair Spray (Mineshaft - Save Room)": SignalisLocationClassification.health,
    "Flare Gun": SignalisLocationClassification.weapon,
    "Signal Flare Shells (Mineshaft - Save Room)": SignalisLocationClassification.ammo,
    "Repair Spray (Mineshaft - STAR/EULR Room)": SignalisLocationClassification.health,
    "12mm Ammo (Mineshaft - STAR/EULR Room)": SignalisLocationClassification.ammo,
    "10mm Ammo (Mineshaft - STAR/EULR Room)": SignalisLocationClassification.ammo,
    "Repair Spray (Mineshaft - Hatch Room)": SignalisLocationClassification.health,
    "10mm Ammo (Mineshaft - Hole Room)": SignalisLocationClassification.ammo,
    "Repair Spray (Mineshaft - Hole Room)": SignalisLocationClassification.health,

    # Nowhere Locations
    "Repair Spray (Nowhere - Morgue)": SignalisLocationClassification.health,
    "Autoinjector (Nowhere - Altar)": SignalisLocationClassification.health,
    "10mm Ammo (Nowhere - Operating Room)": SignalisLocationClassification.ammo,
    "12mm Ammo (Nowhere - Operating Room)": SignalisLocationClassification.ammo,
    "Disposable Stun Prod (Nowhere - Blood Tub Room)": SignalisLocationClassification.ammo,
    "Large Wooden Doll": SignalisLocationClassification.key,
    "Repair Patch (Nowhere - Flesh Hole)": SignalisLocationClassification.health,
    "Nitro Express Ammo (Nowhere - Microphone Room)": SignalisLocationClassification.ammo,
    "Wedding Ring": SignalisLocationClassification.key,
    "Thermite Flare (Nowhere - Save Room After Chimera Boss)": SignalisLocationClassification.ammo,
    "10mm Ammo (Nowhere - Save Room After Chimera Boss)": SignalisLocationClassification.ammo,
    "Repair Patch (Nowhere - Cage Piles #1)": SignalisLocationClassification.health,
    "Disposable Stun Rod (Nowhere - Cage Piles #1)": SignalisLocationClassification.ammo,
    "Signal Flare Shells (Nowhere - Red Ladder Up)": SignalisLocationClassification.ammo,
    "Repair Spray+ (Nowhere - Tentacle Room)": SignalisLocationClassification.health,
    "Regent's Ring": SignalisLocationClassification.key,
    "Small Bottle": SignalisLocationClassification.weapon,
    "Repair Spray (Nowhere - Barbwire Room #1)": SignalisLocationClassification.health,
    "Plate of Flesh": SignalisLocationClassification.key,
    "Rusted Key": SignalisLocationClassification.key,
    "Serpent Ring": SignalisLocationClassification.key,
    "Shotgun Rounds (Nowhere - Dark Hall)": SignalisLocationClassification.ammo,
    "10mm Ammo (Nowhere - Cage Piles #2)": SignalisLocationClassification.ammo,
    "Nitro Express Ammo (Nowhere - Cage Piles #2)": SignalisLocationClassification.ammo,
    "Signal Flare Shells (Nowhere - Crowded Room)": SignalisLocationClassification.ammo,
    "Small Wooden Doll": SignalisLocationClassification.key,
    "Shotgun Rounds (Nowhere - Crowded Room)": SignalisLocationClassification.ammo,
    "Repair Spray+ (Nowhere - Hummingbird Corridor)": SignalisLocationClassification.health,
    "Shotgun Rounds (Nowhere - Hummingbird Corridor)": SignalisLocationClassification.ammo,
    "Grenade Shells (Nowhere - Lamp Room)": SignalisLocationClassification.ammo,
    "Incense": SignalisLocationClassification.key,
    "10mm Ammo (Nowhere - Empress Room)": SignalisLocationClassification.ammo,
    "Plate of Balance": SignalisLocationClassification.key,
    "Plate of Knowledge": SignalisLocationClassification.key,
    "12mm Ammo (Nowhere - Interrogation Room)": SignalisLocationClassification.ammo,
    "Wooden Doll": SignalisLocationClassification.key,
    "Grenade Shells (Nowhere - Interrogation Room)": SignalisLocationClassification.ammo,
    "Repair Spray (Nowhere - Barbwire Room #2)": SignalisLocationClassification.health,
    "Plate of Sacrifice": SignalisLocationClassification.key,
    "Plate of Love": SignalisLocationClassification.key,

    # Corrupted Installation AEON Locations
    "Grenade Shells (Corrupted Installation Aeon - Classroom 4B)": SignalisLocationClassification.ammo,
    "Classroom Key (Corrupted Installation Aeon)": SignalisLocationClassification.key,

    # Rotfront Locations
    "Thermite Flare (Rotfront - Blockwart Bedroom)": SignalisLocationClassification.ammo,
    "Repair Patch (Rotfront - Blockwart Bedroom)": SignalisLocationClassification.health,
    "Submachine Gun": SignalisLocationClassification.weapon,
    "8mm Ammo (Rotfront - Blockwart Office)": SignalisLocationClassification.ammo,
    "Grenade Shells (Rotfront - Ruined Apartment)": SignalisLocationClassification.ammo,
    "Shotgun Rounds (Rotfront - Ruined Apartment)": SignalisLocationClassification.ammo,
    "10mm Ammo (Rotfront - Dormitory)": SignalisLocationClassification.ammo,
    "Repair Spray (Rotfront - Dormitory)": SignalisLocationClassification.health,
    "Repair Spray (Rotfront - Apartment North of Blue Hallway)": SignalisLocationClassification.health,
    "12mm Ammo (Rotfront - Apartment North of Blue Hallway)": SignalisLocationClassification.ammo,
    "Handwheel": SignalisLocationClassification.key,
    "Nitro Express Ammo (Rotfront - Apartment North of Blue Hallway)": SignalisLocationClassification.ammo,
    "Developing Tank": SignalisLocationClassification.key,
    "Repair Spray+ (Rotfront - Atrium)": SignalisLocationClassification.health,
    "Signal Flare Shells (Rotfront - Hospital Hallway)": SignalisLocationClassification.ammo,
    "Autoinjector (Rotfront - Hospital Room)": SignalisLocationClassification.health,
    "Store Key": SignalisLocationClassification.key,
    "Star": SignalisLocationClassification.key,
    "12mm Ammo (Rotfront - Garbage Chute)": SignalisLocationClassification.ammo,
    "Blue Diskette": SignalisLocationClassification.key,
    "Acetone": SignalisLocationClassification.key,
    "Disposable Stun Prod (Rotfront - Meat Grinder)": SignalisLocationClassification.ammo,
    "Repair Spray (Rotfront - Public House)": SignalisLocationClassification.health,
    "8mm Ammo (Rotfront - Public House)": SignalisLocationClassification.ammo,
    "Shotgun Rounds (Rotfront - Public House)": SignalisLocationClassification.ammo,
    "Tower": SignalisLocationClassification.key,
    "10mm Ammo (Rotfront - Metro Platform)": SignalisLocationClassification.ammo,
    "Disposable Stun Prod (Rotfront - Metro Platform)": SignalisLocationClassification.ammo,
    "Repair Spray (Rotfront - Computer Store)": SignalisLocationClassification.health,
    "Patient Key": SignalisLocationClassification.key,
    "12mm Ammo (Rotfront - Fire Escape)": SignalisLocationClassification.ammo,
    "Disposable Stun Prod (Rotfront - Apartment North of Alley)": SignalisLocationClassification.ammo,
    "Repair Spray (Rotfront - Apartment North of Alley)": SignalisLocationClassification.health,
    "Thermite Flare (Rotfront - Butterfly Room)": SignalisLocationClassification.ammo,
    "Nitro Express Ammo (Rotfront - Butterfly Room)": SignalisLocationClassification.ammo,
    "Shotgun Rounds (Rotfront - Dentist Room)": SignalisLocationClassification.ammo,
    "Repair Patch (Rotfront - Dentist Room)": SignalisLocationClassification.health,
    "Red Diskette": SignalisLocationClassification.key,
    "8mm Ammo (Rotfront - Dentist Room)": SignalisLocationClassification.ammo,
    "Moon": SignalisLocationClassification.key,
    "8mm Ammo (Rotfront - Photo Store)": SignalisLocationClassification.ammo,
    "Developer Fluid": SignalisLocationClassification.key,
    "Sun": SignalisLocationClassification.key,
    "Death": SignalisLocationClassification.key,
    "Autoinjector (Rotfront - Book Store)": SignalisLocationClassification.health,
    "Key of Sacrifice": SignalisLocationClassification.key,
    "Lovers": SignalisLocationClassification.key,
    "Dial": SignalisLocationClassification.key
}