name: Bug Report
description: File a bug report.
title: "Bug: "
labels:
  - bug / fix
body:
  - type: markdown
    attributes:
      value: |
        If reporting a bug, please copy your MelonLoader log (all of it!), save it to a text file, and upload it along with your report. Thank you!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
