name: Feature Request
description: Request a feature
title: "Feature Request: "
labels:
  - enhancement
body:
  - type: textarea
    id: feature
    attributes:
      label: Enter your suggestion below.
